<?php

namespace Karamvirs\HereTrigger\Constants;

class Operators {
    const LESS_THAN = 'LESS_THAN';
    const LESS_THAN_EQUAL_TO = 'LESS_THAN_EQUAL_TO';
    const GREATER_THAN = 'GREATER_THAN';
    const GREATER_THAN_EQUAL_TO = 'GREATER_THAN_EQUAL_TO';
    const NUMBER_EQUAL_TO = 'NUMBER_EQUAL_TO';
    const NUMBER_NOT_EQUAL_TO = 'NUMBER_NOT_EQUAL_TO';
    const RANGE_INCLUSIVE = 'RANGE_INCLUSIVE';
    const RANGE_EXCLUSIVE = 'RANGE_EXCLUSIVE';
    const TEXT_CONTAINS = 'TEXT_CONTAINS';
    const DATE_GREATER_THAN_OR_EQUAL_TO = 'DATE_GREATER_THAN_OR_EQUAL_TO';
    const DATE_LESS_THAN_OR_EQUAL_TO = 'DATE_LESS_THAN_OR_EQUAL_TO';
    const DATE_EQUAL_TO = 'DATE_EQUAL_TO';
    const DATE_NOT_EQUAL_TO = 'DATE_NOT_EQUAL_TO';
    const DATE_BETWEEN_INCLUSIVE = 'DATE_BETWEEN_INCLUSIVE';
    const DATE_BETWEEN_EXCLUSIVE = 'DATE_BETWEEN_EXCLUSIVE';
}